export enum AUDIT_ACTIONS {
    BID_PLACED = "BID_PLACED",
    BID_REMOVED = "BID_REMOVED",
    AUCTION_CREATED = "AUCTION_CREATED",
    AUCTION_UPDATED = "AUCTION_UPDATED",
    AUCTION_CANCELLED = "AUCTION_CANCELLED",
    WALLET_UPDATED = "WALLET_UPDATED",
    DEPOSIT_REQUESTED = "DEPOSIT_REQUESTED",
    DEPOSIT_APPROVED = "DEPOSIT_APPROVED",
    DEPOSIT_REJECTED = "DEPOSIT_REJECTED",
}
